# Repository
repo_name: gl-inet/docs3.x
repo_url: https://github.com/gl-inet/docs3.x
edit_uri: ""

site_name: GL.iNet Docs
site_description: Documentation for GL.iNet Productions
site_author: Shan
site_url: https://docs.gl-inet.com/

site_dir: '/home/ubuntu/docs-build/en/3/'

# Copyright
copyright: 'Copyright &copy; 2018 GL Technologies & Microuter Technologies'

theme: 
  name: 'material'
  feature:
    tabs: true
  custom_dir: 'mkdocs-material-sourcecode/material'

# Customization
extra:
  social:
    - type: globe
      link: https://www.gl-inet.com
    - type: github-alt
      link: https://github.com/gl-inet/
    - type: facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - type: twitter
      link: https://twitter.com/GLiNetWiFi
    - type: linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - type: youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg?view_as=subscriber
    - type: pinterest
      link: https://www.pinterest.com/glinetWiFi/

pages:
- Home:
    - Home: 'index.md'
    - Services: 'service.md'
- Hardware:
    - GL-AR150: 'hardware/ar150/index.md'
    - GL-AR300M: 'hardware/ar300m/index.md'
    - GL-MT300A: 'hardware/mt300a/index.md'
    - GL-MT300N: 'hardware/mt300n/index.md'
    - GL-MT300N-V2: 'hardware/mt300n-v2/index.md'
    - GL-AR750: 'hardware/ar750/index.md'
    - GL-AR750S: 'hardware/ar750s/index.md'
    - GL-MiFi: 'hardware/mifi/index.md'
    - GL-USB150: 'hardware/usb150/index.md'
    - GL-B1300: 'hardware/b1300/index.md'
    - Domino Core: 'hardware/domino-core/index.md'
- Setup:
    - Mini Router:
        - First-time Setup: 'setup/mini_router/first-time_setup.md'
        - Admin Panel:
            - Internet: 'setup/mini_router/internet.md'
            - Wireless: 'setup/mini_router/wireless.md'
            - Clients: 'setup/mini_router/clients.md'
            - Upgrade: 'setup/mini_router/upgrade.md'
            - VPN: 'setup/mini_router/vpn.md'
            - Applications: 'setup/mini_router/applications.md'
            - More Settings: 'setup/mini_router/more_settings.md'
    - Travel AC Router:
        - First-time Setup: 'setup/travel_ac_router/first-time_setup.md'
        - Admin Panel:
            - Internet: 'setup/travel_ac_router/internet.md'
            - Wireless: 'setup/travel_ac_router/wireless.md'
            - Clients: 'setup/travel_ac_router/clients.md'
            - Upgrade: 'setup/travel_ac_router/upgrade.md'
            - VPN: 'setup/travel_ac_router/vpn.md'
            - Applications: 'setup/travel_ac_router/applications.md'
            - More Settings: 'setup/travel_ac_router/more_settings.md'
    - 4G Smart Router:
        - First-time Setup: 'setup/4g_smart_router/first-time_setup.md'
        - Admin Panel:
            - Internet: 'setup/4g_smart_router/internet.md'
            - Wireless: 'setup/4g_smart_router/wireless.md'
            - Clients: 'setup/4g_smart_router/clients.md'
            - Upgrade: 'setup/4g_smart_router/upgrade.md'
            - VPN: 'setup/4g_smart_router/vpn.md'
            - Applications: 'setup/4g_smart_router/applications.md'
            - More Settings: 'setup/4g_smart_router/more_settings.md'
    - Microuter:
        - First-time Setup: 'setup/microuter/first-time_setup.md'
        - Admin Panel:
            - Internet: 'setup/microuter/internet.md'
            - Wireless: 'setup/microuter/wireless.md'
            - Clients: 'setup/microuter/clients.md'
            - Upgrade: 'setup/microuter/upgrade.md'
            - VPN: 'setup/microuter/vpn.md'
            - Applications: 'setup/microuter/applications.md'
            - More Settings: 'setup/microuter/more_settings.md'
        
- Development:
    - UART Serial: 'dev/serial.md'
    - Advanced Uboot: 'dev/uboot.md'
- Application:
    - SSH to the router: 'app/ssh.md'
    - OpenVPN: 'app/openvpn.md'
    - Tor: 'app/tor.md'
    - EasyTether: 'app/tether.md'
    - Shadowsocks: 'app/ss.md'
    - WireGuard: 'app/wireguard.md'
    - qDslrDashboard: 'app/qdslrdashboard.md'
- Video:
    - Product Intro: 'video/product_intro.md'
    - Tutorial: 'video/tutor.md'  
    - Customer Review: 'video/review.md'
- Troubleshooting:
    - LED Indicators: 'troubleshooting/led.md'
    - Repair or Reset: 'troubleshooting/reset.md'
    - Debrick via Uboot: 'troubleshooting/debrick.md'
# Extension theme
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
