# Repository
repo_name: gl-inet/docs3.x
repo_url: https://github.com/gl-inet/docs3.x
edit_uri: ""

site_name: GL.iNet Docs
site_description: Documentation for GL.iNet Productions
site_author: Shan
site_url: https://docs.gl-inet.com/
google_analytics: ['UA-108265653-1', 'glinet.com']
site_dir: '/home/ubuntu/docs-build/en/3/'

# Copyright
copyright: 'Copyright &copy; 2020 GL Technologies & Microuter Technologies'

theme: 
  name: 'material'
  feature:
    tabs: true
  custom_dir: 'mkdocs-material-sourcecode/material'

# Customization
extra:
  social:
    - type: globe
      link: https://www.gl-inet.com
    - type: github-alt
      link: https://github.com/gl-inet/
    - type: facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - type: twitter
      link: https://twitter.com/GLiNetWiFi
    - type: linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - type: youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg?view_as=subscriber
    - type: pinterest
      link: https://www.pinterest.com/glinetWiFi/

pages:
- Home:
    - Home: 'index.md'
    - Services: 'service.md'
- Hardware:
    - GL-AR150: 'hardware/ar150/index.md'
    - GL-AR300M: 'hardware/ar300m/index.md'
    - GL-MT300A: 'hardware/mt300a/index.md'
    - GL-MT300N: 'hardware/mt300n/index.md'
    - GL-MT300N-V2: 'hardware/mt300n-v2/index.md'
    - GL-AR750: 'hardware/ar750/index.md'
    - GL-AR750S: 'hardware/ar750s/index.md'
    - GL-MiFi: 'hardware/mifi/index.md'
    - GL-X750: 'hardware/x750/index.md'
    - GL-USB150: 'hardware/usb150/index.md'
    - GL-B1300: 'hardware/b1300/index.md'
    - GL-S1300: 'hardware/s1300/index.md'
    - microuter-N300: 'hardware/microuter-n300/index.md'
    - GL-MV1000: 'hardware/mv1000/index.md'
    - GL-X1200: 'hardware/x1200/index.md'
    - Domino Core: 'hardware/domino-core/index.md'
- Setup:
    - Mini Router Series:
        - First-time Setup: 'setup/mini_router/first-time_setup.md'
        - Internet: 'setup/mini_router/internet.md'
        - Wireless: 'setup/mini_router/wireless.md'
        - Clients: 'setup/mini_router/clients.md'
        - Upgrade: 'setup/mini_router/upgrade.md'
        - Firewall: 'setup/mini_router/firewall.md'
        - VPN: 'setup/mini_router/vpn.md'
        - Applications: 'setup/mini_router/applications.md'
        - More Settings: 'setup/mini_router/more_settings.md'
    - Travel AC Router (GL-AR750):
        - First-time Setup: 'setup/travel_ac_router/first-time_setup.md'
        - Internet: 'setup/travel_ac_router/internet.md'
        - Wireless: 'setup/travel_ac_router/wireless.md'
        - Clients: 'setup/travel_ac_router/clients.md'
        - Upgrade: 'setup/travel_ac_router/upgrade.md'
        - Firewall: 'setup/travel_ac_router/firewall.md'
        - VPN: 'setup/travel_ac_router/vpn.md'
        - Applications: 'setup/travel_ac_router/applications.md'
        - More Settings: 'setup/travel_ac_router/more_settings.md'
    - Slate (GL-AR750S-Ext):
        - First-time Setup: 'setup/slate/first-time_setup.md'
        - Internet: 'setup/slate/internet.md'
        - Wireless: 'setup/slate/wireless.md'
        - Clients: 'setup/slate/clients.md'
        - Upgrade: 'setup/slate/upgrade.md'
        - Firewall: 'setup/slate/firewall.md'
        - VPN: 'setup/slate/vpn.md'
        - Applications: 'setup/slate/applications.md'
        - More Settings: 'setup/slate/more_settings.md'
    - 4G Smart Router (GL-MiFi):
        - First-time Setup: 'setup/4g_smart_router/first-time_setup.md'
        - Internet: 'setup/4g_smart_router/internet.md'
        - Wireless: 'setup/4g_smart_router/wireless.md'
        - Clients: 'setup/4g_smart_router/clients.md'
        - Upgrade: 'setup/4g_smart_router/upgrade.md'
        - VPN: 'setup/4g_smart_router/vpn.md'
        - Applications: 'setup/4g_smart_router/applications.md'
        - More Settings: 'setup/4g_smart_router/more_settings.md'
    - Spitz (GL-X750):
        - First-time Setup: 'setup/spitz/first-time_setup.md'
        - Internet: 'setup/spitz/internet.md'
        - Wireless: 'setup/spitz/wireless.md'
        - Clients: 'setup/spitz/clients.md'
        - Upgrade: 'setup/spitz/upgrade.md'
        - VPN: 'setup/spitz/vpn.md'
        - Applications: 'setup/spitz/applications.md'
        - More Settings: 'setup/spitz/more_settings.md'
    - Microuter (GL-USB150):
        - First-time Setup: 'setup/microuter/first-time_setup.md'
        - Internet: 'setup/microuter/internet.md'
        - Wireless: 'setup/microuter/wireless.md'
        - Clients: 'setup/microuter/clients.md'
        - Upgrade: 'setup/microuter/upgrade.md'
        - VPN: 'setup/microuter/vpn.md'
        - Applications: 'setup/microuter/applications.md'
        - More Settings: 'setup/microuter/more_settings.md'
    - VIXMINI:
        - First-time Setup: 'setup/vixmini/first-time_setup.md'
        - Internet: 'setup/vixmini/internet.md'
        - Wireless: 'setup/vixmini/wireless.md'
        - Clients: 'setup/vixmini/clients.md'
        - Upgrade: 'setup/vixmini/upgrade.md'
        - Applications: 'setup/vixmini/applications.md'
        - More Settings: 'setup/vixmini/more_settings.md'
    - Convexa-B (GL-B1300):
        - First-time Setup: 'setup/convexa_b/first-time_setup.md'
        - Internet: 'setup/convexa_b/internet.md'
        - Wireless: 'setup/convexa_b/wireless.md'
        - Mesh: 'setup/convexa_b/mesh.md'
        - Clients: 'setup/convexa_b/clients.md'
        - Upgrade: 'setup/convexa_b/upgrade.md'
        - Firewall: 'setup/convexa_b/firewall.md'
        - VPN: 'setup/convexa_b/vpn.md'
        - Applications: 'setup/convexa_b/applications.md'
        - More Settings: 'setup/convexa_b/more_settings.md'
    - Convexa-S (GL-S1300):
        - First-time Setup: 'setup/convexa_s/first-time_setup.md'
        - Internet: 'setup/convexa_s/internet.md'
        - Wireless: 'setup/convexa_s/wireless.md'
        - Mesh: 'setup/convexa_s/mesh.md'
        - Clients: 'setup/convexa_s/clients.md'
        - Upgrade: 'setup/convexa_s/upgrade.md'
        - Firewall: 'setup/convexa_s/firewall.md'
        - VPN: 'setup/convexa_s/vpn.md'
        - Applications: 'setup/convexa_s/applications.md'
        - More Settings: 'setup/convexa_s/more_settings.md'
    - microuter-N300:
        - First-time Setup: 'setup/microuter-n300/first-time_setup.md'
        - Internet: 'setup/microuter-n300/internet.md'
        - Wireless: 'setup/microuter-n300/wireless.md'
        - Clients: 'setup/microuter-n300/clients.md'
        - Upgrade: 'setup/microuter-n300/upgrade.md'
        - VPN: 'setup/microuter-n300/vpn.md'
        - Applications: 'setup/microuter-n300/applications.md'
        - More Settings: 'setup/microuter-n300/more_settings.md'
    - Brume (GL-MV1000):
        - First-time Setup: 'setup/brume/first-time_setup.md'
        - Internet: 'setup/brume/internet.md'
        - Clinets: 'setup/brume/clients.md'
        - Upgrade: 'setup/brume/upgrade.md'
        - Firewall: 'setup/brume/firewall.md'
        - VPN: 'setup/brume/vpn.md'
        - Applications: 'setup/brume/applications.md'
        - More Settings: 'setup/brume/more_settings.md'
    - Mudi (GL-E750):
        - First-time Setup: 'setup/mudi/first-time_setup.md'
        - Internet: 'setup/mudi/internet.md'
        - Wireless: 'setup/mudi/wireless.md'
        - Clinets: 'setup/mudi/clients.md'
        - Upgrade: 'setup/mudi/upgrade.md'
        - Firewall: 'setup/mudi/firewall.md'
        - VPN: 'setup/mudi/vpn.md'
        - Applications: 'setup/mudi/applications.md'
        - More Settings: 'setup/mudi/more_settings.md'
    - Amarok (GL-X1200):
        - First-time Setup: 'setup/gl-x1200/first-time_setup.md'
    - GL-S10:
        - First-time Setup: 'setup/gl-s10/first-time_setup.md'
        - API Manual: 'setup/gl-s10/api_manual.md'
        - Firmware Complilation Guide: 'setup/gl-s10/firmware_compilation_guide.md'
        
- Development:
    - UART Serial: 'dev/serial.md'
    - Advanced Uboot: 'dev/uboot.md'
- Application:
    - SSH to the router: 'app/ssh.md'
    - OpenVPN: 'app/openvpn.md'
    - Shadowsocks: 'app/ss.md'
    - WireGuard: 'app/wireguard.md'
    - VPN Policies: 'app/vpn_policies.md'
    - File Sharing: 'app/file_sharing.md'
    - DLNA Server: 'app/dlnaserver.md'
    - DDNS: 'app/ddns.md'
    - Cloud: 'app/cloud.md'
    - LED Customization: 'app/led_customization.md'
    - Set a Captive Portal: 'app/captive_portal.md'
    - BLE MQTT Bridge: 'app/ble2mqtt.md'
    - qDslrDashboard: 'app/qdslrdashboard.md'
    - EasyTether: 'app/tether.md'
    - Tor: 'app/tor.md'
    - Canera: 'app/camera.md'
- Video:
    - Product Intro: 'video/product_intro.md'
    - Tutorial: 'video/tutor.md'  
    - Customer Review: 'video/review.md'
- Troubleshooting:
    - LED Indicators: 'troubleshooting/led.md'
    - Repair or Reset: 'troubleshooting/reset.md'
    - Debrick via Uboot: 'troubleshooting/debrick.md'
    - Change WAN to LAN: 'troubleshooting/chang_wan_to_lan.md'
    - Captive Portal: 'troubleshooting/captive_portal.md'
    - Repeat Failure: 'troubleshooting/repeat_failure.md'
    - Use GL.iNet app: 'troubleshooting/use_glinet_app.md'
    - FAQs: 'troubleshooting/FAQ.md'
- Release Notes:
    - Firmware Releases: 'release_notes/index.md'
    - GL-AR150: 'release_notes/GL-AR150.md'
    - GL-AR300M: 'release_notes/GL-AR300M.md'
    - GL-MT300A: 'release_notes/GL-MT300A.md'
    - GL-MT300N: 'release_notes/GL-MT300N.md'
    - GL-MT300N-V2: 'release_notes/GL-MT300N-V2.md'
    - GL-AR750: 'release_notes/GL-AR750.md'
    - GL-AR750S-Ext: 'release_notes/GL-AR750S-Ext.md'
    - GL-MiFi: 'release_notes/GL-MiFi.md'
    - GL-X750: 'release_notes/GL-X750.md'
    - GL-USB150: 'release_notes/GL-USB150.md'
    - GL-B1300: 'release_notes/GL-B1300.md'
    - GL-S1300: 'release_notes/GL-S1300.md'
    - VIXMINI: 'release_notes/VIXMINI.md'
    - GL-MV1000: 'release_notes/GL-MV1000.md'
    - GL-X1200: 'release_notes/GL-X1200.md'
    - GL-E750: 'release_notes/GL-E750.md'
    - microuter-N300: 'release_notes/microuter-N300.md'
# Extension theme
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
