# Repository
repo_name: gl-inet/docs3.x
repo_url: https://github.com/gl-inet/docs3.x
edit_uri: ""

site_name: GL.iNet Docs
site_description: Documentation for GL.iNet Productions
site_author: Shan
site_url: https://docs.gl-inet.com/
google_analytics: ['UA-108265653-1', 'glinet.com']
site_dir: '/home/ubuntu/docs-build/en/3/'

# Copyright
copyright: 'Copyright &copy; 2019 GL Technologies & Microuter Technologies'

theme: 
  name: 'material'
  feature:
    tabs: true
  custom_dir: 'mkdocs-material-sourcecode/material'
  language: 'ja'

# Customization
extra:
  social:
    - type: globe
      link: https://www.gl-inet.com
    - type: github-alt
      link: https://github.com/gl-inet/
    - type: facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - type: twitter
      link: https://twitter.com/GLiNetWiFi
    - type: linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - type: youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg?view_as=subscriber
    - type: pinterest
      link: https://www.pinterest.com/glinetWiFi/

pages:
- Home:
    - Home: 'index.md'
    - Services: 'service.md'
- Hardware:
    - GL-AR150: 'hardware/ar150/index.md'
    - GL-AR300M: 'hardware/ar300m/index.md'
    - GL-MT300A: 'hardware/mt300a/index.md'
    - GL-MT300N: 'hardware/mt300n/index.md'
    - GL-MT300N-V2: 'hardware/mt300n-v2/index.md'
    - GL-AR750: 'hardware/ar750/index.md'
    - GL-AR750S: 'hardware/ar750s/index.md'
    - GL-MiFi: 'hardware/mifi/index.md'
    - GL-USB150: 'hardware/usb150/index.md'
    - GL-B1300: 'hardware/b1300/index.md'
    - Domino Core: 'hardware/domino-core/index.md'
- セットアップ:
    - ナノルーター:
        - 基本設定: 'setup/mini_router/first-time_setup.md'
        - ネットワーク: 'setup/mini_router/internet.md'
        - 無線: 'setup/mini_router/wireless.md'
        - クライアント: 'setup/mini_router/clients.md'
        - アップグレード: 'setup/mini_router/upgrade.md'
        - VPN: 'setup/mini_router/vpn.md'
        - アプリケーション: 'setup/mini_router/applications.md'
        - その他の設定: 'setup/mini_router/more_settings.md'
    - Travel AC Router (GL-AR750):
        - First-time Setup: 'setup/travel_ac_router/first-time_setup.md'
        - Internet: 'setup/travel_ac_router/internet.md'
        - Wireless: 'setup/travel_ac_router/wireless.md'
        - Clients: 'setup/travel_ac_router/clients.md'
        - Upgrade: 'setup/travel_ac_router/upgrade.md'
        - Firewall: 'setup/travel_ac_router/firewall.md'
        - VPN: 'setup/travel_ac_router/vpn.md'
        - Applications: 'setup/travel_ac_router/applications.md'
        - More Settings: 'setup/travel_ac_router/more_settings.md'
    - Slate (GL-AR750S-Ext):
        - First-time Setup: 'setup/slate/first-time_setup.md'
        - Internet: 'setup/slate/internet.md'
        - Wireless: 'setup/slate/wireless.md'
        - Clients: 'setup/slate/clients.md'
        - Upgrade: 'setup/slate/upgrade.md'
        - Firewall: 'setup/slate/firewall.md'
        - VPN: 'setup/slate/vpn.md'
        - Applications: 'setup/slate/applications.md'
        - More Settings: 'setup/slate/more_settings.md'
    - 4G Smart Router (GL-MiFi):
        - First-time Setup: 'setup/4g_smart_router/first-time_setup.md'
        - Internet: 'setup/4g_smart_router/internet.md'
        - Wireless: 'setup/4g_smart_router/wireless.md'
        - Clients: 'setup/4g_smart_router/clients.md'
        - Upgrade: 'setup/4g_smart_router/upgrade.md'
        - VPN: 'setup/4g_smart_router/vpn.md'
        - Applications: 'setup/4g_smart_router/applications.md'
        - More Settings: 'setup/4g_smart_router/more_settings.md'
    - Spitz (GL-X750):
        - First-time Setup: 'setup/spitz/first-time_setup.md'
        - Internet: 'setup/spitz/internet.md'
        - Wireless: 'setup/spitz/wireless.md'
        - Clients: 'setup/spitz/clients.md'
        - Upgrade: 'setup/spitz/upgrade.md'
        - VPN: 'setup/spitz/vpn.md'
        - Applications: 'setup/spitz/applications.md'
        - More Settings: 'setup/spitz/more_settings.md'
    - Microuter (GL-USB150):
        - First-time Setup: 'setup/microuter/first-time_setup.md'
        - Internet: 'setup/microuter/internet.md'
        - Wireless: 'setup/microuter/wireless.md'
        - Clients: 'setup/microuter/clients.md'
        - Upgrade: 'setup/microuter/upgrade.md'
        - VPN: 'setup/microuter/vpn.md'
        - Applications: 'setup/microuter/applications.md'
        - More Settings: 'setup/microuter/more_settings.md'
    - VIXMINI:
        - First-time Setup: 'setup/vixmini/first-time_setup.md'
        - Internet: 'setup/vixmini/internet.md'
        - Wireless: 'setup/vixmini/wireless.md'
        - Clients: 'setup/vixmini/clients.md'
        - Upgrade: 'setup/vixmini/upgrade.md'
        - Applications: 'setup/vixmini/applications.md'
        - More Settings: 'setup/vixmini/more_settings.md'
        
- Development:
    - UART Serial: 'dev/serial.md'
    - Advanced Uboot: 'dev/uboot.md'
- Application:
    - SSH to the router: 'app/ssh.md'
    - OpenVPN: 'app/openvpn.md'
    - Tor: 'app/tor.md'
    - EasyTether: 'app/tether.md'
    - Shadowsocks: 'app/ss.md'
    - WireGuard: 'app/wireguard.md'
    - qDslrDashboard: 'app/qdslrdashboard.md'
    - File Sharing: 'app/file_sharing.md'
    - DDNS: 'app/ddns.md'
    - Cloud: 'app/cloud.md'
- Video:
    - Product Intro: 'video/product_intro.md'
    - Tutorial: 'video/tutor.md'  
    - Customer Review: 'video/review.md'
- 問題解決:
    - LED Indicators: 'troubleshooting/led.md'
    - Repair or Reset: 'troubleshooting/reset.md'
    - Ubootハードウエア修復: 'troubleshooting/debrick.md'
    - Change WAN to LAN: 'troubleshooting/chang_wan_to_lan.md'
    - Captive Portal: 'troubleshooting/captive_portal.md'
    - FAQs: 'troubleshooting/FAQ.md'
- Release Notes:
    - Firmware Releases: 'release_notes/index.md'
    - GL-AR150: 'release_notes/GL-AR150.md'
    - GL-AR300M: 'release_notes/GL-AR300M.md'
    - GL-MT300A: 'release_notes/GL-MT300A.md'
    - GL-MT300N: 'release_notes/GL-MT300N.md'
    - GL-MT300N-V2: 'release_notes/GL-MT300N-V2.md'
    - GL-AR750: 'release_notes/GL-AR750.md'
    - GL-AR750S-Ext: 'release_notes/GL-AR750S-Ext.md'
    - GL-MiFi: 'release_notes/GL-MiFi.md'
    - GL-X750: 'release_notes/GL-X750.md'
    - GL-USB150: 'release_notes/GL-USB150.md'
    - GL-B1300: 'release_notes/GL-B1300.md'
    - VIXMINI: 'release_notes/VIXMINI.md'
# Extension theme
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
