# Repository
repo_name: gl-inet/docs3.x
repo_url: https://github.com/gl-inet/docs3.x
edit_uri: ""

site_name: GL.iNet Docs
site_description: Documentation for GL.iNet Productions
site_author: GL.iNet
site_url: https://docs.gl-inet.com/en/3/
site_dir: /home/ubuntu/docs-build/en/3/
copyright: Copyright &copy; 2021 GL Technologies & Microuter Technologies

theme: 
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: images/favicon.png

# Customization
extra:
  analytics:
    provider: google
    property: UA-108265653-5
  social:
    - icon: fontawesome/solid/globe
      link: https://www.gl-inet.com
    - icon: fontawesome/brands/github
      link: https://github.com/gl-inet/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GLiNetWiFi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg?view_as=subscriber
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/glinetWiFi/
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Japanese
      link: /jp/
      lang: ja

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css
  # we can use the cdn or files
  # - stylesheets/photoswipe.min.css
  # - stylesheets/default-skin.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js
  # we can use the cdn or files
  # - javascripts/photoswipe.min.js
  # - javascripts/photoswipe-ui-default.min.js
  - javascripts/extra.js

markdown_extensions:
  - attr_list

nav:
  - Home:
    - Overview: index.md
    - Services: service.md
  - Specification:
    - Overview: specification/index.md
    - GL-AR150: specification/gl-ar150/index.md
    - GL-AR300M: specification/gl-ar300m/index.md
    - GL-MT300N-V2: specification/gl-mt300n-v2/index.md
    - GL-AR750: specification/gl-ar750/index.md
    - GL-AR750S: specification/gl-ar750s/index.md
    - GL-MT1300: specification/gl-mt1300/index.md
    - GL-AX1800: specification/gl-ax1800/index.md
    - GL-MiFi: specification/gl-mifi/index.md
    - GL-XE300: specification/gl-xe300/index.md
    - GL-X750: specification/gl-x750/index.md
    - GL-E750: specification/gl-e750/index.md
    - GL-USB150: specification/gl-usb150/index.md
    - GL-B1300: specification/gl-b1300/index.md
    - GL-S1300: specification/gl-s1300/index.md
    - GL-MV1000: specification/gl-mv1000/index.md
    - GL-MV1000W: specification/gl-mv1000w/index.md
    - GL-X1200: specification/gl-x1200/index.md
    - GL-X300B: specification/gl-x300b/index.md
    - GL-AP1300: specification/gl-ap1300/index.md
    - GL-B2200: specification/gl-b2200/index.md
    - GL-SF1200: specification/gl-sf1200/index.md
    - microuter-N300: specification/microuter-n300/index.md
    - Domino Core: specification/domino-core/index.md
    - GL-MT300A: specification/gl-mt300a/index.md
    - GL-MT300N: specification/gl-mt300n/index.md
  - Setup:
    - Overview: setup/index.md
    - Mini Router Series:
      - First-time Setup: setup/mini_router/first-time_setup.md
      - Internet: setup/mini_router/internet.md
      - Wireless: setup/mini_router/wireless.md
      - Clients: setup/mini_router/clients.md
      - Upgrade: setup/mini_router/upgrade.md
      - Firewall: setup/mini_router/firewall.md
      - VPN: setup/mini_router/vpn.md
      - Applications: setup/mini_router/applications.md
      - More Settings: setup/mini_router/more_settings.md
    - Creta (GL-AR750):
      - First-time Setup: setup/gl-ar750/first-time_setup.md
      - Internet: setup/gl-ar750/internet.md
      - Wireless: setup/gl-ar750/wireless.md
      - Clients: setup/gl-ar750/clients.md
      - Upgrade: setup/gl-ar750/upgrade.md
      - Firewall: setup/gl-ar750/firewall.md
      - VPN: setup/gl-ar750/vpn.md
      - Applications: setup/gl-ar750/applications.md
      - More Settings: setup/gl-ar750/more_settings.md
    - Slate (GL-AR750S-Ext):
      - First-time Setup: setup/gl-ar750s/first-time_setup.md
      - Internet: setup/gl-ar750s/internet.md
      - Wireless: setup/gl-ar750s/wireless.md
      - Clients: setup/gl-ar750s/clients.md
      - Upgrade: setup/gl-ar750s/upgrade.md
      - Firewall: setup/gl-ar750s/firewall.md
      - VPN: setup/gl-ar750s/vpn.md
      - Applications: setup/gl-ar750s/applications.md
      - More Settings: setup/gl-ar750s/more_settings.md
    - Beryl (GL-MT1300):
      - First-time Setup: setup/gl-mt1300/first-time_setup.md
      - Internet: setup/gl-mt1300/internet.md
      - Wireless: setup/gl-mt1300/wireless.md
      - Clients: setup/gl-mt1300/clients.md
      - Upgrade: setup/gl-mt1300/upgrade.md
      - Firewall: setup/gl-mt1300/firewall.md
      - VPN: setup/gl-mt1300/vpn.md
      - Applications: setup/gl-mt1300/applications.md
      - More Settings: setup/gl-mt1300/more_settings.md
    - 4G Smart Router (GL-MiFi):
      - First-time Setup: setup/gl-mifi/first-time_setup.md
      - Internet: setup/gl-mifi/internet.md
      - Wireless: setup/gl-mifi/wireless.md
      - Clients: setup/gl-mifi/clients.md
      - Upgrade: setup/gl-mifi/upgrade.md
      - VPN: setup/gl-mifi/vpn.md
      - Applications: setup/gl-mifi/applications.md
      - More Settings: setup/gl-mifi/more_settings.md
    - Puli (GL-XE300):
      - First-time Setup: setup/gl-xe300/first-time_setup.md
      - Internet: setup/gl-xe300/internet.md
      - Wireless: setup/gl-xe300/wireless.md
      - Clients: setup/gl-xe300/clients.md
      - Upgrade: setup/gl-xe300/upgrade.md
      - Firewall: setup/gl-xe300/firewall.md
      - VPN: setup/gl-xe300/vpn.md
      - Applications: setup/gl-xe300/applications.md
      - More Settings: setup/gl-xe300/more_settings.md
    - Spitz (GL-X750):
      - First-time Setup: setup/gl-x750/first-time_setup.md
      - Internet: setup/gl-x750/internet.md
      - Wireless: setup/gl-x750/wireless.md
      - Clients: setup/gl-x750/clients.md
      - Upgrade: setup/gl-x750/upgrade.md
      - VPN: setup/gl-x750/vpn.md
      - Applications: setup/gl-x750/applications.md
      - More Settings: setup/gl-x750/more_settings.md
    - Mudi (GL-E750):
      - First-time Setup: setup/gl-e750/first-time_setup.md
      - Internet: setup/gl-e750/internet.md
      - Wireless: setup/gl-e750/wireless.md
      - Clients: setup/gl-e750/clients.md
      - Upgrade: setup/gl-e750/upgrade.md
      - Firewall: setup/gl-e750/firewall.md
      - VPN: setup/gl-e750/vpn.md
      - Applications: setup/gl-e750/applications.md
      - More Settings: setup/gl-e750/more_settings.md
    - Microuter (GL-USB150):
      - First-time Setup: setup/gl-usb150/first-time_setup.md
      - Internet: setup/gl-usb150/internet.md
      - Wireless: setup/gl-usb150/wireless.md
      - Clients: setup/gl-usb150/clients.md
      - Upgrade: setup/gl-usb150/upgrade.md
      - VPN: setup/gl-usb150/vpn.md
      - Applications: setup/gl-usb150/applications.md
      - More Settings: setup/gl-usb150/more_settings.md
    - Convexa-B (GL-B1300):
      - First-time Setup: setup/gl-b1300/first-time_setup.md
      - Internet: setup/gl-b1300/internet.md
      - Wireless: setup/gl-b1300/wireless.md
      - Mesh: setup/gl-b1300/mesh.md
      - Clients: setup/gl-b1300/clients.md
      - Upgrade: setup/gl-b1300/upgrade.md
      - Firewall: setup/gl-b1300/firewall.md
      - VPN: setup/gl-b1300/vpn.md
      - Applications: setup/gl-b1300/applications.md
      - More Settings: setup/gl-b1300/more_settings.md
    - Convexa-S (GL-S1300):
      - First-time Setup: setup/gl-s1300/first-time_setup.md
      - Internet: setup/gl-s1300/internet.md
      - Wireless: setup/gl-s1300/wireless.md
      - Mesh: setup/gl-s1300/mesh.md
      - Clients: setup/gl-s1300/clients.md
      - Upgrade: setup/gl-s1300/upgrade.md
      - Firewall: setup/gl-s1300/firewall.md
      - VPN: setup/gl-s1300/vpn.md
      - Applications: setup/gl-s1300/applications.md
      - More Settings: setup/gl-s1300/more_settings.md
    - Velica (GL-B2200):
      - First-time Setup: setup/gl-b2200/first-time_setup.md
      - Internet: setup/gl-b2200/internet.md
      - Wireless: setup/gl-b2200/wireless.md
      - Mesh: setup/gl-b2200/mesh.md
      - Clients: setup/gl-b2200/clients.md
      - Upgrade: setup/gl-b2200/upgrade.md
      - Firewall: setup/gl-b2200/firewall.md
      - VPN: setup/gl-b2200/vpn.md
      - Applications: setup/gl-b2200/applications.md
      - More Settings: setup/gl-b2200/more_settings.md
    - Brume (GL-MV1000):
      - First-time Setup: setup/gl-mv1000/first-time_setup.md
      - Internet: setup/gl-mv1000/internet.md
      - Wireless: setup/gl-mv1000/wireless.md
      - Clients: setup/gl-mv1000/clients.md
      - Upgrade: setup/gl-mv1000/upgrade.md
      - Firewall: setup/gl-mv1000/firewall.md
      - VPN: setup/gl-mv1000/vpn.md
      - Applications: setup/gl-mv1000/applications.md
      - More Settings: setup/gl-mv1000/more_settings.md
    - Brume-W (GL-MV1000W):
      - First-time Setup: setup/gl-mv1000w/first-time_setup.md
      - Internet: setup/gl-mv1000w/internet.md
      - Wireless: setup/gl-mv1000w/wireless.md
      - Clients: setup/gl-mv1000w/clients.md
      - Upgrade: setup/gl-mv1000w/upgrade.md
      - Firewall: setup/gl-mv1000w/firewall.md
      - VPN: setup/gl-mv1000w/vpn.md
      - Applications: setup/gl-mv1000w/applications.md
      - More Settings: setup/gl-mv1000w/more_settings.md
    - GL-SF1200:
      - First-time Setup: setup/gl-sf1200/first-time_setup.md
      - Internet: setup/gl-sf1200/internet.md
      - Wireless: setup/gl-sf1200/wireless.md
      - Clients: setup/gl-sf1200/clients.md
      - Upgrade: setup/gl-sf1200/upgrade.md
      - Firewall: setup/gl-sf1200/firewall.md
      - VPN: setup/gl-sf1200/vpn.md
      - Applications: setup/gl-sf1200/applications.md
      - More Settings: setup/gl-sf1200/more_settings.md
    - Amarok (GL-X1200):
      - First-time Setup: setup/gl-x1200/first-time_setup.md
    - Collie (GL-X300B):
      - First-time Setup: setup/gl-x300b/first-time_setup.md
    - GL-S10:
      - First-time Setup: setup/gl-s10/first-time_setup.md
      - API Manual: setup/gl-s10/api_manual.md
      - Firmware Complilation Guide: setup/gl-s10/firmware_compilation_guide.md
    - Cirrus (GL-AP1300/GL-AP1300LTE):
      - First-time Setup: setup/gl-ap1300/first-time_setup.md
      - Internet: setup/gl-ap1300/internet.md
      - Wireless: setup/gl-ap1300/wireless.md
      - Clients: setup/gl-ap1300/clients.md
      - Upgrade: setup/gl-ap1300/upgrade.md
      - Firewall: setup/gl-ap1300/firewall.md
      - VPN: setup/gl-ap1300/vpn.md
      - Applications: setup/gl-ap1300/applications.md
      - More Settings: setup/gl-ap1300/more_settings.md
    - microuter-N300:
      - First-time Setup: setup/microuter-n300/first-time_setup.md
      - Internet: setup/microuter-n300/internet.md
      - Wireless: setup/microuter-n300/wireless.md
      - Clients: setup/microuter-n300/clients.md
      - Upgrade: setup/microuter-n300/upgrade.md
      - VPN: setup/microuter-n300/vpn.md
      - Applications: setup/microuter-n300/applications.md
      - More Settings: setup/microuter-n300/more_settings.md
    - VIXMINI:
      - First-time Setup: setup/vixmini/first-time_setup.md
      - Internet: setup/vixmini/internet.md
      - Wireless: setup/vixmini/wireless.md
      - Clients: setup/vixmini/clients.md
      - Upgrade: setup/vixmini/upgrade.md
      - Applications: setup/vixmini/applications.md
      - More Settings: setup/vixmini/more_settings.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Repeater: tutorials/repeater.md
    - Firmware Upgrade: tutorials/firmware_upgrade.md
    - SSH to the Router: tutorials/ssh.md
    - Copy files to Router: tutorials/scp.md
    - OpenVPN Client: tutorials/openvpn_client.md
    - OpenVPN Server: tutorials/openvpn_server.md
    - OpenVPN Bridge: tutorials/openvpn_bridge.md
    - WireGuard Client: tutorials/wireguard_client.md
    - WireGuard Server: tutorials/wireguard_server.md
    - Internet Kill Switch: tutorials/internet_kill_switch.md
    - Change WAN to LAN: tutorials/change_wan_to_lan.md
    - VPN Policies: tutorials/vpn_policies.md
    - File Sharing: tutorials/file_sharing.md
    - DLNA Server: tutorials/dlnaserver.md
    - DDNS: tutorials/ddns.md
    - Cloud: tutorials/cloud.md
    - NextDNS: tutorials/nextdns.md
    - Mobile App: tutorials/mobile_app.md
    - SMS Forward: tutorials/sms_forward.md
    - LED Customization: tutorials/led_customization.md
    - Setup Captive Portal: tutorials/captive_portal.md
    - Connect to Captive Portal: tutorials/connect_to_a_hotspot_with_captive_portal.md
    - BLE MQTT Bridge: tutorials/ble2mqtt.md
    - qDslrDashboard: tutorials/qdslrdashboard.md
    - EasyTether: tutorials/tether.md
    - Tor: tutorials/tor.md
    - Camera: tutorials/camera.md
  - Development:
    - UART Serial: dev/serial.md
    - Advanced Uboot: dev/uboot.md
  - Video:
    - Product Intro: video/product_intro.md
    - Tutorial: video/tutor.md  
    - Customer Review: video/review.md
    - Unboxing: video/unboxing.md
  - Troubleshooting:
    # - Overview: troubleshooting/index.md
    - LED Indicators: troubleshooting/led.md
    - Repair or Reset: troubleshooting/reset.md
    - Debrick via Uboot: troubleshooting/debrick.md
    - Captive Portal: troubleshooting/captive_portal.md
    - Repeat Failure: troubleshooting/repeat_failure.md
    - Access Web Panel: troubleshooting/access_web_panel.md
    - Extensible Authentication Protocol: troubleshooting/eap.md
    - GoodCloud issues: troubleshooting/goodcloud.md
    - Modem FAQ: troubleshooting/modem_faq.md
    - FAQs: troubleshooting/faq.md
  - Release Notes:
    - Firmware Releases: release_notes/index.md
    - GL-AR150: release_notes/GL-AR150.md
    - GL-AR300M: release_notes/GL-AR300M.md
    - GL-MT300N-V2: release_notes/GL-MT300N-V2.md
    - GL-MT1300: release_notes/GL-MT1300.md
    - GL-AR750: release_notes/GL-AR750.md
    - GL-AR750S-Ext: release_notes/GL-AR750S-Ext.md
    - GL-MiFi: release_notes/GL-MiFi.md
    - GL-XE300: release_notes/GL-XE300.md
    - GL-X300B: release_notes/GL-X300B.md
    - GL-X750: release_notes/GL-X750.md
    - GL-E750: release_notes/GL-E750.md
    - GL-USB150: release_notes/GL-USB150.md
    - GL-B2200: release_notes/GL-B2200.md
    - GL-B1300: release_notes/GL-B1300.md
    - GL-S1300: release_notes/GL-S1300.md
    - GL-SF1200: release_notes/GL-SF1200.md
    - GL-MV1000: release_notes/GL-MV1000.md
    - GL-X1200: release_notes/GL-X1200.md
    - GL-AP1300: release_notes/GL-AP1300.md
    - microuter-N300: release_notes/microuter-N300.md
    - VIXMINI: release_notes/VIXMINI.md
    - GL-MT300A: release_notes/GL-MT300A.md
    - GL-MT300N: release_notes/GL-MT300N.md
