# Repository
repo_name: gl-inet/docs3.x
repo_url: https://github.com/gl-inet/docs3.x
edit_uri: ""

site_name: GL.iNet Docs
site_description: Documentation for GL.iNet Productions
site_author: Shan
site_url: https://docs.gl-inet.com/jp/3/
site_dir: /home/ubuntu/docs-build/jp/3/
copyright: 'Copyright &copy; 2021 GL Technologies & Microuter Technologies'

theme: 
  name: material
  logo: images/logo.svg
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: 'ja'
  favicon: images/favicon.png

# Customization
extra:
  analytics:
    provider: google
    property: UA-108265653-5
  social:
    - icon: fontawesome/solid/globe
      link: https://www.gl-inet.com
    - icon: fontawesome/brands/github
      link: https://github.com/gl-inet/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GLiNetWiFi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg?view_as=subscriber
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/glinetWiFi/
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Japanese
      link: /jp/
      lang: ja

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css
  # we can use the cdn or files
  # - stylesheets/photoswipe.min.css
  # - stylesheets/default-skin.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js
  # we can use the cdn or files
  # - javascripts/photoswipe.min.js
  # - javascripts/photoswipe-ui-default.min.js
  - javascripts/extra.js

markdown_extensions:
  - attr_list
  - pymdownx.tabbed

nav:
  - ホーム:
    - ホーム: index.md
    - サービス: service.md
  - ハードウエア:
    - GL-AR300M: hardware/gl-ar300m/index.md
    - GL-MT300N-V2: hardware/gl-mt300n-v2/index.md
    - GL-AR750: hardware/gl-ar750/index.md
    - GL-AR750S: hardware/gl-ar750s/index.md
    - GL-XE300: hardware/gl-xe300/index.md
    - GL-MT1300: hardware/gl-mt1300/index.md
    - GL-MV1000: hardware/gl-mv1000/index.md
    - GL-B2200: hardware/gl-b2200/index.md
    - GL-AX1800: hardware/gl-ax1800/index.md
    - microuter-N300: hardware/microuter-n300/index.md
  - セットアップ:
    - ナノルーター:
      - 基本設定: setup/mini_router/first-time_setup.md
      - ネットワーク: setup/mini_router/internet.md
      - 無線: setup/mini_router/wireless.md
      - クライアント: setup/mini_router/clients.md
      - アップグレード: setup/mini_router/upgrade.md
      - ファイアウォール: setup/mini_router/firewall.md
      - VPN: setup/mini_router/vpn.md
      - アプリケーション: setup/mini_router/applications.md
      - その他の設定: setup/mini_router/more_settings.md
    - GL-AR750(Creta):
      - 基本設定: setup/gl-ar750/first-time_setup.md
      - ネットワーク: setup/gl-ar750/internet.md
      - 無線: setup/gl-ar750/wireless.md
      - クライアント: setup/gl-ar750/clients.md
      - アップグレード: setup/gl-ar750/upgrade.md
      - ファイアウォール: setup/gl-ar750/firewall.md
      - VPN: setup/gl-ar750/vpn.md
      - アプリケーション: setup/gl-ar750/applications.md
      - その他の設定: setup/gl-ar750/more_settings.md
    - GL-AR750S-EXT(Slate):
      - 基本設定: setup/gl-ar750s/first-time_setup.md
      - ネットワーク: setup/gl-ar750s/internet.md
      - 無線: setup/gl-ar750s/wireless.md
      - クライアント: setup/gl-ar750s/clients.md
      - アップグレード: setup/gl-ar750s/upgrade.md
      - ファイアウォール: setup/gl-ar750s/firewall.md
      - VPN: setup/gl-ar750s/vpn.md
      - アプリケーション: setup/gl-ar750s/applications.md
      - その他の設定: setup/gl-ar750s/more_settings.md
    - GL-MT1300(Beryl):
      - 基本設定: setup/gl-mt1300/first-time_setup.md
      - ネットワーク: setup/gl-mt1300/internet.md
      - 無線: setup/gl-mt1300/wireless.md
      - クライアント: setup/gl-mt1300/clients.md
      - アップグレード: setup/gl-mt1300/upgrade.md
      - ファイアウォール: setup/gl-mt1300/firewall.md
      - VPN: setup/gl-mt1300/vpn.md
      - アプリケーション: setup/gl-mt1300/applications.md
      - その他の設定: setup/gl-mt1300/more_settings.md
    - GL-MV1000(Brume):
      - 基本設定: setup/gl-mv1000/first-time_setup.md
      - ネットワーク: setup/gl-mv1000/internet.md
      - クライアント: setup/gl-mv1000/clients.md
      - アップグレード: setup/gl-mv1000/upgrade.md
      - ファイアウォール: setup/gl-mv1000/firewall.md
      - VPN: setup/gl-mv1000/vpn.md
      - アプリケーション: setup/gl-mv1000/applications.md
      - その他の設定: setup/gl-mv1000/more_settings.md
    - GL-B1300(Convexa-B):
      - 基本設定: setup/gl-b1300/first-time_setup.md
      - ネットワーク: setup/gl-b1300/internet.md
      - 無線: setup/gl-b1300/wireless.md
      - メッシュ: setup/gl-b1300/mesh.md
      - クライアント: setup/gl-b1300/clients.md
      - アップグレード: setup/gl-b1300/upgrade.md
      - ファイアウォール: setup/gl-b1300/firewall.md
      - VPN: setup/gl-b1300/vpn.md
      - アプリケーション: setup/gl-b1300/applications.md
      - その他の設定: setup/gl-b1300/more_settings.md
    - GL-B2200(Velica):
      - 基本設定: setup/gl-b2200/first-time_setup.md
      - ネットワーク: setup/gl-b2200/internet.md
      - 無線: setup/gl-b2200/wireless.md
      - メッシュ: setup/gl-b2200/mesh.md
      - クライアント: setup/gl-b2200/clients.md
      - アップグレード: setup/gl-b2200/upgrade.md
      - ファイアウォール: setup/gl-b2200/firewall.md
      - VPN: setup/gl-b2200/vpn.md
      - アプリケーション: setup/gl-b2200/applications.md
      - その他の設定: setup/gl-b2200/more_settings.md
    - GL-AX1800(Flint):
      - 基本設定: setup/gl-ax1800/first_time_setup.md
      - ネットワーク: setup/gl-ax1800/internet.md
      - 無線: setup/gl-ax1800/wireless.md
      - クライアント: setup/gl-ax1800/clients.md
      - アップグレード: setup/gl-ax1800/upgrade.md
      - ファイアウォール: setup/gl-ax1800/firewall.md
      - VPN: setup/gl-ax1800/vpn.md
      - アプリケーション: setup/gl-ax1800/applications.md
      - その他の設定: setup/gl-ax1800/more_settings.md
    - GL-XE300(Puli):
      - 基本設定: setup/gl-xe300/first-time_setup.md
      - ネットワーク: setup/gl-xe300/internet.md
      - 無線: setup/gl-xe300/wireless.md
      - クライアント: setup/gl-xe300/clients.md
      - アップグレード: setup/gl-xe300/upgrade.md
      - ファイアウォール: setup/gl-xe300/firewall.md
      - VPN: setup/gl-xe300/vpn.md
      - アプリケーション: setup/gl-xe300/applications.md
      - その他の設定: setup/gl-xe300/more_settings.md
  - 開発:
    - UART シリアル: dev/serial.md
  - アプリケーション:
    - ルーターにSSH: app/ssh.md
    - OpenVPN: app/openvpn.md
    - WireGuard: app/wireguard.md
    - ファイル共有: app/file_sharing.md
    - DLNAサーバー: app/dlna.md
    - DDNS: app/ddns.md
    - クラウドサービス: app/cloud.md
  - ビデオ:
    - 製品紹介: video/product_intro.md
    - チュートリアル: video/tutor.md  
    - 顧客レビュー: video/review.md
  - 問題解決:
    - LED 指標: troubleshooting/led.md
    - 修復/リセット: troubleshooting/reset.md
    - ファームウェアを再インストール: troubleshooting/debrick.md
    - WANポートをLANに: troubleshooting/chang_wan_to_lan.md
    - キャプティブポータル: troubleshooting/captive_portal.md
    - よくある質問: troubleshooting/FAQ.md
  - リリースノート:
    - ファームウェア リリース: release_notes/index.md
    - GL-MT300N-V2: release_notes/GL-MT300N-V2.md
    - GL-AR750S-Ext(Slate): release_notes/GL-AR750S-Ext.md
    - GL-AR750(Creta): release_notes/GL-AR750.md
    - GL-AR300M: release_notes/GL-AR300M.md
