# Repository
repo_name: gl-inet/docs3.x
repo_url: https://github.com/gl-inet/docs3.x
edit_uri: ""

site_name: GL.iNet Docs
site_description: Documentation for GL.iNet Productions
site_author: Shan
site_url: https://docs.gl-inet.com/
google_analytics: ['UA-108265653-1', 'glinet.com']
site_dir: '/home/ubuntu/docs-build/jp/3/'

# Copyright
copyright: 'Copyright &copy; 2019 GL Technologies & Microuter Technologies'

theme: 
  name: 'material'
  feature:
    tabs: true
  custom_dir: 'mkdocs-material-sourcecode/material'
  language: 'ja'

# Customization
extra:
  social:
    - type: globe
      link: https://www.gl-inet.com
    - type: github-alt
      link: https://github.com/gl-inet/
    - type: facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - type: twitter
      link: https://twitter.com/GLiNetWiFi
    - type: linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - type: youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg?view_as=subscriber
    - type: pinterest
      link: https://www.pinterest.com/glinetWiFi/

pages:
- ホーム:
    - ホーム: 'index.md'
    - サービス: 'service.md'
- ハードウエア:
    - GL-MT300N-V2: 'hardware/mt300n-v2/index.md'
    - GL-AR750S-Ext: 'hardware/ar750s/index.md'
- セットアップ:
    - ナノルーター:
        - 基本設定: 'setup/mini_router/first-time_setup.md'
        - ネットワーク: 'setup/mini_router/internet.md'
        - 無線: 'setup/mini_router/wireless.md'
        - クライアント: 'setup/mini_router/clients.md'
        - アップグレード: 'setup/mini_router/upgrade.md'
        - ファイアウォール: 'setup/mini_router/firewall.md'
        - VPN: 'setup/mini_router/vpn.md'
        - アプリケーション: 'setup/mini_router/applications.md'
        - その他の設定: 'setup/mini_router/more_settings.md'
    - Slate (GL-AR750S-Ext):
        - 基本設定: 'setup/slate/first-time_setup.md'
        - ネットワーク: 'setup/slate/internet.md'
        - 無線: 'setup/slate/wireless.md'
        - クライアント: 'setup/slate/clients.md'
        - アップグレード: 'setup/slate/upgrade.md'
        - ファイアウォール: 'setup/slate/firewall.md'
        - VPN: 'setup/slate/vpn.md'
        - アプリケーション: 'setup/slate/applications.md'
        - その他の設定: 'setup/slate/more_settings.md'
        
- 開発:
    - UART シリアル: 'dev/serial.md'
- アプリケーション:
    - ルーターにSSH: 'app/ssh.md'
    - OpenVPN: 'app/openvpn.md'
    - WireGuard: 'app/wireguard.md'
    - Shadowsocks: 'app/ss.md'
    - ファイル共有: 'app/file_sharing.md'
    - DDNS: 'app/ddns.md'
    - クラウドサービス: 'app/cloud.md'
- ビデオ:
    - 製品紹介: 'video/product_intro.md'
    - チュートリアル: 'video/tutor.md'  
    - 顧客レビュー: 'video/review.md'
- 問題解決:
    - LED 指標: 'troubleshooting/led.md'
    - 修復/リセット: 'troubleshooting/reset.md'
    - ブリックを修復: 'troubleshooting/debrick.md'
    - WANポートをLANに: 'troubleshooting/chang_wan_to_lan.md'
    - キャプティブポータル: 'troubleshooting/captive_portal.md'
    - よくある質問: 'troubleshooting/FAQ.md'
- リリースノート:
    - ファームウェア リリース: 'release_notes/index.md'
    - GL-MT300N-V2: 'release_notes/GL-MT300N-V2.md'
    - GL-AR750S-Ext(Slate): 'release_notes/GL-AR750S-Ext.md'
# Extension theme
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
